INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (22, NULL, NULL, NULL, NULL, NULL, NULL, 'MATINI');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (23, NULL, NULL, NULL, NULL, NULL, NULL, 'NIKA');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (24, NULL, NULL, NULL, NULL, NULL, NULL, 'ASPO');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (25, NULL, NULL, NULL, NULL, NULL, NULL, 'DEVITA');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (27, NULL, NULL, NULL, NULL, NULL, NULL, 'ALLEN DE LUX');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (30, NULL, NULL, NULL, NULL, NULL, NULL, 'BALUNOVA');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (31, NULL, NULL, NULL, NULL, NULL, NULL, 'NIDA');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (32, NULL, NULL, NULL, NULL, NULL, NULL, 'AXXA');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (33, NULL, NULL, NULL, NULL, NULL, NULL, 'МИР МОДЫ');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (34, NULL, NULL, NULL, NULL, NULL, NULL, 'ANDREA STYLE');
INSERT INTO `brand` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (35, NULL, NULL, NULL, NULL, NULL, NULL, 'PANDA');
