INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (27, NULL, NULL, NULL, NULL, NULL, NULL, 'Разное');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (28, NULL, NULL, NULL, NULL, NULL, NULL, 'Плащи');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (29, NULL, NULL, NULL, NULL, NULL, NULL, 'Пальто');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (30, NULL, NULL, NULL, NULL, NULL, NULL, 'Туники');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (32, NULL, NULL, NULL, NULL, NULL, NULL, 'Свитеры');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (33, NULL, NULL, NULL, NULL, NULL, NULL, 'Блузки');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (34, NULL, NULL, NULL, NULL, NULL, NULL, 'Брюки');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (35, NULL, NULL, NULL, NULL, NULL, NULL, 'Детская одежда');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (36, NULL, NULL, NULL, NULL, NULL, NULL, 'Жакеты');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (37, NULL, NULL, NULL, NULL, NULL, NULL, 'Юбки');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (38, NULL, NULL, NULL, NULL, NULL, NULL, 'Жилеты');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (39, NULL, NULL, NULL, NULL, NULL, NULL, 'Куртки');
INSERT INTO `category` (`id`, `description`, `created`, `modify`, `updated`, `url`, `visible`, `title`) VALUES (40, NULL, NULL, NULL, NULL, NULL, NULL, 'Костюмы');
